# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nothing/Galaga/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/nothing/Galaga

PRODUCT_COPY_FILES += \
    vendor/nothing/Galaga/proprietary/system/etc/sysconfig/nothing-hiddenapi-package-allowlist.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/nothing-hiddenapi-package-allowlist.xml \
    vendor/nothing/Galaga/proprietary/system_ext/etc/permissions/NTCamera-google-permissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/NTCamera-google-permissions.xml \
    vendor/nothing/Galaga/proprietary/system_ext/etc/permissions/NTCamera-permissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/NTCamera-permissions.xml \
    vendor/nothing/Galaga/proprietary/system_ext/etc/permissions/privapp-permissions-NTCamera.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp-permissions-NTCamera.xml \
    vendor/nothing/Galaga/proprietary/system_ext/etc/permissions/privapp-permissions-NothingExperience.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp-permissions-NothingExperience.xml \
    vendor/nothing/Galaga/proprietary/system_ext/priv-app/NTCamera/oat/arm64/NTCamera.odex:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/NTCamera/oat/arm64/NTCamera.odex \
    vendor/nothing/Galaga/proprietary/system_ext/priv-app/NTCamera/oat/arm64/NTCamera.vdex:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/NTCamera/oat/arm64/NTCamera.vdex

PRODUCT_PACKAGES += \
    NTCamera \
    NothingExperience \
    libnelib
